# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\limyreth\git\sysintercept

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\limyreth\git\sysintercept

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\limyreth\git\sysintercept\CMakeFiles C:\Users\limyreth\git\sysintercept\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\limyreth\git\sysintercept\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ncodehook

# Build rule for target.
ncodehook: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ncodehook
.PHONY : ncodehook

# fast build rule for target.
ncodehook/fast:
	$(MAKE) -f CMakeFiles\ncodehook.dir\build.make CMakeFiles/ncodehook.dir/build
.PHONY : ncodehook/fast

#=============================================================================
# Target rules for targets named ninjectlib

# Build rule for target.
ninjectlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 ninjectlib
.PHONY : ninjectlib

# fast build rule for target.
ninjectlib/fast:
	$(MAKE) -f CMakeFiles\ninjectlib.dir\build.make CMakeFiles/ninjectlib.dir/build
.PHONY : ninjectlib/fast

#=============================================================================
# Target rules for targets named sysintercept

# Build rule for target.
sysintercept: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sysintercept
.PHONY : sysintercept

# fast build rule for target.
sysintercept/fast:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/build
.PHONY : sysintercept/fast

#=============================================================================
# Target rules for targets named sysinterceptCommon

# Build rule for target.
sysinterceptCommon: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sysinterceptCommon
.PHONY : sysinterceptCommon

# fast build rule for target.
sysinterceptCommon/fast:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/build
.PHONY : sysinterceptCommon/fast

#=============================================================================
# Target rules for targets named sysinterceptDll

# Build rule for target.
sysinterceptDll: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 sysinterceptDll
.PHONY : sysinterceptDll

# fast build rule for target.
sysinterceptDll/fast:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/build
.PHONY : sysinterceptDll/fast

SyscallInterceptor/interceptconfigshare.obj: SyscallInterceptor/interceptconfigshare.cpp.obj
.PHONY : SyscallInterceptor/interceptconfigshare.obj

# target to build an object file
SyscallInterceptor/interceptconfigshare.cpp.obj:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/interceptconfigshare.cpp.obj
.PHONY : SyscallInterceptor/interceptconfigshare.cpp.obj

SyscallInterceptor/interceptconfigshare.i: SyscallInterceptor/interceptconfigshare.cpp.i
.PHONY : SyscallInterceptor/interceptconfigshare.i

# target to preprocess a source file
SyscallInterceptor/interceptconfigshare.cpp.i:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/interceptconfigshare.cpp.i
.PHONY : SyscallInterceptor/interceptconfigshare.cpp.i

SyscallInterceptor/interceptconfigshare.s: SyscallInterceptor/interceptconfigshare.cpp.s
.PHONY : SyscallInterceptor/interceptconfigshare.s

# target to generate assembly for a file
SyscallInterceptor/interceptconfigshare.cpp.s:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/interceptconfigshare.cpp.s
.PHONY : SyscallInterceptor/interceptconfigshare.cpp.s

SyscallInterceptor/stdafx.obj: SyscallInterceptor/stdafx.cpp.obj
.PHONY : SyscallInterceptor/stdafx.obj

# target to build an object file
SyscallInterceptor/stdafx.cpp.obj:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/stdafx.cpp.obj
.PHONY : SyscallInterceptor/stdafx.cpp.obj

SyscallInterceptor/stdafx.i: SyscallInterceptor/stdafx.cpp.i
.PHONY : SyscallInterceptor/stdafx.i

# target to preprocess a source file
SyscallInterceptor/stdafx.cpp.i:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/stdafx.cpp.i
.PHONY : SyscallInterceptor/stdafx.cpp.i

SyscallInterceptor/stdafx.s: SyscallInterceptor/stdafx.cpp.s
.PHONY : SyscallInterceptor/stdafx.s

# target to generate assembly for a file
SyscallInterceptor/stdafx.cpp.s:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/stdafx.cpp.s
.PHONY : SyscallInterceptor/stdafx.cpp.s

SyscallInterceptor/sysintercept.obj: SyscallInterceptor/sysintercept.cpp.obj
.PHONY : SyscallInterceptor/sysintercept.obj

# target to build an object file
SyscallInterceptor/sysintercept.cpp.obj:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/sysintercept.cpp.obj
.PHONY : SyscallInterceptor/sysintercept.cpp.obj

SyscallInterceptor/sysintercept.i: SyscallInterceptor/sysintercept.cpp.i
.PHONY : SyscallInterceptor/sysintercept.i

# target to preprocess a source file
SyscallInterceptor/sysintercept.cpp.i:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/sysintercept.cpp.i
.PHONY : SyscallInterceptor/sysintercept.cpp.i

SyscallInterceptor/sysintercept.s: SyscallInterceptor/sysintercept.cpp.s
.PHONY : SyscallInterceptor/sysintercept.s

# target to generate assembly for a file
SyscallInterceptor/sysintercept.cpp.s:
	$(MAKE) -f CMakeFiles\sysintercept.dir\build.make CMakeFiles/sysintercept.dir/SyscallInterceptor/sysintercept.cpp.s
.PHONY : SyscallInterceptor/sysintercept.cpp.s

SyscallInterceptorCommon/charset.obj: SyscallInterceptorCommon/charset.cpp.obj
.PHONY : SyscallInterceptorCommon/charset.obj

# target to build an object file
SyscallInterceptorCommon/charset.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/charset.cpp.obj
.PHONY : SyscallInterceptorCommon/charset.cpp.obj

SyscallInterceptorCommon/charset.i: SyscallInterceptorCommon/charset.cpp.i
.PHONY : SyscallInterceptorCommon/charset.i

# target to preprocess a source file
SyscallInterceptorCommon/charset.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/charset.cpp.i
.PHONY : SyscallInterceptorCommon/charset.cpp.i

SyscallInterceptorCommon/charset.s: SyscallInterceptorCommon/charset.cpp.s
.PHONY : SyscallInterceptorCommon/charset.s

# target to generate assembly for a file
SyscallInterceptorCommon/charset.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/charset.cpp.s
.PHONY : SyscallInterceptorCommon/charset.cpp.s

SyscallInterceptorCommon/logging.obj: SyscallInterceptorCommon/logging.cpp.obj
.PHONY : SyscallInterceptorCommon/logging.obj

# target to build an object file
SyscallInterceptorCommon/logging.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/logging.cpp.obj
.PHONY : SyscallInterceptorCommon/logging.cpp.obj

SyscallInterceptorCommon/logging.i: SyscallInterceptorCommon/logging.cpp.i
.PHONY : SyscallInterceptorCommon/logging.i

# target to preprocess a source file
SyscallInterceptorCommon/logging.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/logging.cpp.i
.PHONY : SyscallInterceptorCommon/logging.cpp.i

SyscallInterceptorCommon/logging.s: SyscallInterceptorCommon/logging.cpp.s
.PHONY : SyscallInterceptorCommon/logging.s

# target to generate assembly for a file
SyscallInterceptorCommon/logging.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/logging.cpp.s
.PHONY : SyscallInterceptorCommon/logging.cpp.s

SyscallInterceptorCommon/stdafx.obj: SyscallInterceptorCommon/stdafx.cpp.obj
.PHONY : SyscallInterceptorCommon/stdafx.obj

# target to build an object file
SyscallInterceptorCommon/stdafx.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/stdafx.cpp.obj
.PHONY : SyscallInterceptorCommon/stdafx.cpp.obj

SyscallInterceptorCommon/stdafx.i: SyscallInterceptorCommon/stdafx.cpp.i
.PHONY : SyscallInterceptorCommon/stdafx.i

# target to preprocess a source file
SyscallInterceptorCommon/stdafx.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/stdafx.cpp.i
.PHONY : SyscallInterceptorCommon/stdafx.cpp.i

SyscallInterceptorCommon/stdafx.s: SyscallInterceptorCommon/stdafx.cpp.s
.PHONY : SyscallInterceptorCommon/stdafx.s

# target to generate assembly for a file
SyscallInterceptorCommon/stdafx.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptCommon.dir\build.make CMakeFiles/sysinterceptCommon.dir/SyscallInterceptorCommon/stdafx.cpp.s
.PHONY : SyscallInterceptorCommon/stdafx.cpp.s

SyscallInterceptorDll/config.obj: SyscallInterceptorDll/config.cpp.obj
.PHONY : SyscallInterceptorDll/config.obj

# target to build an object file
SyscallInterceptorDll/config.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/config.cpp.obj
.PHONY : SyscallInterceptorDll/config.cpp.obj

SyscallInterceptorDll/config.i: SyscallInterceptorDll/config.cpp.i
.PHONY : SyscallInterceptorDll/config.i

# target to preprocess a source file
SyscallInterceptorDll/config.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/config.cpp.i
.PHONY : SyscallInterceptorDll/config.cpp.i

SyscallInterceptorDll/config.s: SyscallInterceptorDll/config.cpp.s
.PHONY : SyscallInterceptorDll/config.s

# target to generate assembly for a file
SyscallInterceptorDll/config.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/config.cpp.s
.PHONY : SyscallInterceptorDll/config.cpp.s

SyscallInterceptorDll/dllmain.obj: SyscallInterceptorDll/dllmain.cpp.obj
.PHONY : SyscallInterceptorDll/dllmain.obj

# target to build an object file
SyscallInterceptorDll/dllmain.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/dllmain.cpp.obj
.PHONY : SyscallInterceptorDll/dllmain.cpp.obj

SyscallInterceptorDll/dllmain.i: SyscallInterceptorDll/dllmain.cpp.i
.PHONY : SyscallInterceptorDll/dllmain.i

# target to preprocess a source file
SyscallInterceptorDll/dllmain.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/dllmain.cpp.i
.PHONY : SyscallInterceptorDll/dllmain.cpp.i

SyscallInterceptorDll/dllmain.s: SyscallInterceptorDll/dllmain.cpp.s
.PHONY : SyscallInterceptorDll/dllmain.s

# target to generate assembly for a file
SyscallInterceptorDll/dllmain.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/dllmain.cpp.s
.PHONY : SyscallInterceptorDll/dllmain.cpp.s

SyscallInterceptorDll/interceptconfig.obj: SyscallInterceptorDll/interceptconfig.cpp.obj
.PHONY : SyscallInterceptorDll/interceptconfig.obj

# target to build an object file
SyscallInterceptorDll/interceptconfig.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/interceptconfig.cpp.obj
.PHONY : SyscallInterceptorDll/interceptconfig.cpp.obj

SyscallInterceptorDll/interceptconfig.i: SyscallInterceptorDll/interceptconfig.cpp.i
.PHONY : SyscallInterceptorDll/interceptconfig.i

# target to preprocess a source file
SyscallInterceptorDll/interceptconfig.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/interceptconfig.cpp.i
.PHONY : SyscallInterceptorDll/interceptconfig.cpp.i

SyscallInterceptorDll/interceptconfig.s: SyscallInterceptorDll/interceptconfig.cpp.s
.PHONY : SyscallInterceptorDll/interceptconfig.s

# target to generate assembly for a file
SyscallInterceptorDll/interceptconfig.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/interceptconfig.cpp.s
.PHONY : SyscallInterceptorDll/interceptconfig.cpp.s

SyscallInterceptorDll/parse.obj: SyscallInterceptorDll/parse.cpp.obj
.PHONY : SyscallInterceptorDll/parse.obj

# target to build an object file
SyscallInterceptorDll/parse.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/parse.cpp.obj
.PHONY : SyscallInterceptorDll/parse.cpp.obj

SyscallInterceptorDll/parse.i: SyscallInterceptorDll/parse.cpp.i
.PHONY : SyscallInterceptorDll/parse.i

# target to preprocess a source file
SyscallInterceptorDll/parse.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/parse.cpp.i
.PHONY : SyscallInterceptorDll/parse.cpp.i

SyscallInterceptorDll/parse.s: SyscallInterceptorDll/parse.cpp.s
.PHONY : SyscallInterceptorDll/parse.s

# target to generate assembly for a file
SyscallInterceptorDll/parse.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/parse.cpp.s
.PHONY : SyscallInterceptorDll/parse.cpp.s

SyscallInterceptorDll/replacement.obj: SyscallInterceptorDll/replacement.cpp.obj
.PHONY : SyscallInterceptorDll/replacement.obj

# target to build an object file
SyscallInterceptorDll/replacement.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/replacement.cpp.obj
.PHONY : SyscallInterceptorDll/replacement.cpp.obj

SyscallInterceptorDll/replacement.i: SyscallInterceptorDll/replacement.cpp.i
.PHONY : SyscallInterceptorDll/replacement.i

# target to preprocess a source file
SyscallInterceptorDll/replacement.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/replacement.cpp.i
.PHONY : SyscallInterceptorDll/replacement.cpp.i

SyscallInterceptorDll/replacement.s: SyscallInterceptorDll/replacement.cpp.s
.PHONY : SyscallInterceptorDll/replacement.s

# target to generate assembly for a file
SyscallInterceptorDll/replacement.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/replacement.cpp.s
.PHONY : SyscallInterceptorDll/replacement.cpp.s

SyscallInterceptorDll/stdafx.obj: SyscallInterceptorDll/stdafx.cpp.obj
.PHONY : SyscallInterceptorDll/stdafx.obj

# target to build an object file
SyscallInterceptorDll/stdafx.cpp.obj:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/stdafx.cpp.obj
.PHONY : SyscallInterceptorDll/stdafx.cpp.obj

SyscallInterceptorDll/stdafx.i: SyscallInterceptorDll/stdafx.cpp.i
.PHONY : SyscallInterceptorDll/stdafx.i

# target to preprocess a source file
SyscallInterceptorDll/stdafx.cpp.i:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/stdafx.cpp.i
.PHONY : SyscallInterceptorDll/stdafx.cpp.i

SyscallInterceptorDll/stdafx.s: SyscallInterceptorDll/stdafx.cpp.s
.PHONY : SyscallInterceptorDll/stdafx.s

# target to generate assembly for a file
SyscallInterceptorDll/stdafx.cpp.s:
	$(MAKE) -f CMakeFiles\sysinterceptDll.dir\build.make CMakeFiles/sysinterceptDll.dir/SyscallInterceptorDll/stdafx.cpp.s
.PHONY : SyscallInterceptorDll/stdafx.cpp.s

ncodehook/NCodeHook.obj: ncodehook/NCodeHook.cpp.obj
.PHONY : ncodehook/NCodeHook.obj

# target to build an object file
ncodehook/NCodeHook.cpp.obj:
	$(MAKE) -f CMakeFiles\ncodehook.dir\build.make CMakeFiles/ncodehook.dir/ncodehook/NCodeHook.cpp.obj
.PHONY : ncodehook/NCodeHook.cpp.obj

ncodehook/NCodeHook.i: ncodehook/NCodeHook.cpp.i
.PHONY : ncodehook/NCodeHook.i

# target to preprocess a source file
ncodehook/NCodeHook.cpp.i:
	$(MAKE) -f CMakeFiles\ncodehook.dir\build.make CMakeFiles/ncodehook.dir/ncodehook/NCodeHook.cpp.i
.PHONY : ncodehook/NCodeHook.cpp.i

ncodehook/NCodeHook.s: ncodehook/NCodeHook.cpp.s
.PHONY : ncodehook/NCodeHook.s

# target to generate assembly for a file
ncodehook/NCodeHook.cpp.s:
	$(MAKE) -f CMakeFiles\ncodehook.dir\build.make CMakeFiles/ncodehook.dir/ncodehook/NCodeHook.cpp.s
.PHONY : ncodehook/NCodeHook.cpp.s

ncodehook/NCodeHookItem.obj: ncodehook/NCodeHookItem.cpp.obj
.PHONY : ncodehook/NCodeHookItem.obj

# target to build an object file
ncodehook/NCodeHookItem.cpp.obj:
	$(MAKE) -f CMakeFiles\ncodehook.dir\build.make CMakeFiles/ncodehook.dir/ncodehook/NCodeHookItem.cpp.obj
.PHONY : ncodehook/NCodeHookItem.cpp.obj

ncodehook/NCodeHookItem.i: ncodehook/NCodeHookItem.cpp.i
.PHONY : ncodehook/NCodeHookItem.i

# target to preprocess a source file
ncodehook/NCodeHookItem.cpp.i:
	$(MAKE) -f CMakeFiles\ncodehook.dir\build.make CMakeFiles/ncodehook.dir/ncodehook/NCodeHookItem.cpp.i
.PHONY : ncodehook/NCodeHookItem.cpp.i

ncodehook/NCodeHookItem.s: ncodehook/NCodeHookItem.cpp.s
.PHONY : ncodehook/NCodeHookItem.s

# target to generate assembly for a file
ncodehook/NCodeHookItem.cpp.s:
	$(MAKE) -f CMakeFiles\ncodehook.dir\build.make CMakeFiles/ncodehook.dir/ncodehook/NCodeHookItem.cpp.s
.PHONY : ncodehook/NCodeHookItem.cpp.s

ninjectlib/IATModifier.obj: ninjectlib/IATModifier.cpp.obj
.PHONY : ninjectlib/IATModifier.obj

# target to build an object file
ninjectlib/IATModifier.cpp.obj:
	$(MAKE) -f CMakeFiles\ninjectlib.dir\build.make CMakeFiles/ninjectlib.dir/ninjectlib/IATModifier.cpp.obj
.PHONY : ninjectlib/IATModifier.cpp.obj

ninjectlib/IATModifier.i: ninjectlib/IATModifier.cpp.i
.PHONY : ninjectlib/IATModifier.i

# target to preprocess a source file
ninjectlib/IATModifier.cpp.i:
	$(MAKE) -f CMakeFiles\ninjectlib.dir\build.make CMakeFiles/ninjectlib.dir/ninjectlib/IATModifier.cpp.i
.PHONY : ninjectlib/IATModifier.cpp.i

ninjectlib/IATModifier.s: ninjectlib/IATModifier.cpp.s
.PHONY : ninjectlib/IATModifier.s

# target to generate assembly for a file
ninjectlib/IATModifier.cpp.s:
	$(MAKE) -f CMakeFiles\ninjectlib.dir\build.make CMakeFiles/ninjectlib.dir/ninjectlib/IATModifier.cpp.s
.PHONY : ninjectlib/IATModifier.cpp.s

ninjectlib/Process.obj: ninjectlib/Process.cpp.obj
.PHONY : ninjectlib/Process.obj

# target to build an object file
ninjectlib/Process.cpp.obj:
	$(MAKE) -f CMakeFiles\ninjectlib.dir\build.make CMakeFiles/ninjectlib.dir/ninjectlib/Process.cpp.obj
.PHONY : ninjectlib/Process.cpp.obj

ninjectlib/Process.i: ninjectlib/Process.cpp.i
.PHONY : ninjectlib/Process.i

# target to preprocess a source file
ninjectlib/Process.cpp.i:
	$(MAKE) -f CMakeFiles\ninjectlib.dir\build.make CMakeFiles/ninjectlib.dir/ninjectlib/Process.cpp.i
.PHONY : ninjectlib/Process.cpp.i

ninjectlib/Process.s: ninjectlib/Process.cpp.s
.PHONY : ninjectlib/Process.s

# target to generate assembly for a file
ninjectlib/Process.cpp.s:
	$(MAKE) -f CMakeFiles\ninjectlib.dir\build.make CMakeFiles/ninjectlib.dir/ninjectlib/Process.cpp.s
.PHONY : ninjectlib/Process.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... ncodehook
	@echo ... ninjectlib
	@echo ... rebuild_cache
	@echo ... sysintercept
	@echo ... sysinterceptCommon
	@echo ... sysinterceptDll
	@echo ... SyscallInterceptor/interceptconfigshare.obj
	@echo ... SyscallInterceptor/interceptconfigshare.i
	@echo ... SyscallInterceptor/interceptconfigshare.s
	@echo ... SyscallInterceptor/stdafx.obj
	@echo ... SyscallInterceptor/stdafx.i
	@echo ... SyscallInterceptor/stdafx.s
	@echo ... SyscallInterceptor/sysintercept.obj
	@echo ... SyscallInterceptor/sysintercept.i
	@echo ... SyscallInterceptor/sysintercept.s
	@echo ... SyscallInterceptorCommon/charset.obj
	@echo ... SyscallInterceptorCommon/charset.i
	@echo ... SyscallInterceptorCommon/charset.s
	@echo ... SyscallInterceptorCommon/logging.obj
	@echo ... SyscallInterceptorCommon/logging.i
	@echo ... SyscallInterceptorCommon/logging.s
	@echo ... SyscallInterceptorCommon/stdafx.obj
	@echo ... SyscallInterceptorCommon/stdafx.i
	@echo ... SyscallInterceptorCommon/stdafx.s
	@echo ... SyscallInterceptorDll/config.obj
	@echo ... SyscallInterceptorDll/config.i
	@echo ... SyscallInterceptorDll/config.s
	@echo ... SyscallInterceptorDll/dllmain.obj
	@echo ... SyscallInterceptorDll/dllmain.i
	@echo ... SyscallInterceptorDll/dllmain.s
	@echo ... SyscallInterceptorDll/interceptconfig.obj
	@echo ... SyscallInterceptorDll/interceptconfig.i
	@echo ... SyscallInterceptorDll/interceptconfig.s
	@echo ... SyscallInterceptorDll/parse.obj
	@echo ... SyscallInterceptorDll/parse.i
	@echo ... SyscallInterceptorDll/parse.s
	@echo ... SyscallInterceptorDll/replacement.obj
	@echo ... SyscallInterceptorDll/replacement.i
	@echo ... SyscallInterceptorDll/replacement.s
	@echo ... SyscallInterceptorDll/stdafx.obj
	@echo ... SyscallInterceptorDll/stdafx.i
	@echo ... SyscallInterceptorDll/stdafx.s
	@echo ... ncodehook/NCodeHook.obj
	@echo ... ncodehook/NCodeHook.i
	@echo ... ncodehook/NCodeHook.s
	@echo ... ncodehook/NCodeHookItem.obj
	@echo ... ncodehook/NCodeHookItem.i
	@echo ... ncodehook/NCodeHookItem.s
	@echo ... ninjectlib/IATModifier.obj
	@echo ... ninjectlib/IATModifier.i
	@echo ... ninjectlib/IATModifier.s
	@echo ... ninjectlib/Process.obj
	@echo ... ninjectlib/Process.i
	@echo ... ninjectlib/Process.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

